### ISSUE TITLE
Error n.map on highlight two m.c. questions and copy paste

### ISSUE THREAD

**Issue by malvidah** [kaspnilsson/curyte-issues#4]
**Describe the bug**
Highlighting and copy pasting 2 multiple choice questions breaks the editor and sends an n.map error

**To Reproduce**
1. Go to 'lesson editor'
2. Click on 'add quiz question'
3. select two quiz questions
4. copy and paste them
5. error message

**Expected behavior**
paste 2 mc questions

**Screenshots**
![image](https://user-images.githubusercontent.com/77100405/151266772-cbef39cb-53b5-4617-9807-61df98e53f4f.png)

**Desktop (please complete the following information):**
 - OSX
 - chrome

**Smartphone (please complete the following information):**
 - iOS

**Comment by kaspnilsson** [comment]
In fact, copy and paste is broken for even just ONE quiz question!
